In [1]:
import os
import sys
import pandas as pd
import numpy as np
import requests
import json
import matplotlib.pyplot as plt
import seaborn as sns
import time
import moodys_keys as mk
from EDFXAuthentication import EDFXClient
from EDFXPrime import EDFXEndpoints, OutputFormat, FinancialTemplate

In [2]:
#  This is how this method works In [3]:  # testing client class Instantiation
public  = mk.EDF_X()['Client'],# EDFX public key
private = mk.EDF_X()['Client_Secret'], # EDFX private key.
#test instantiation
client = EDFXClient(public,private)
# print(client)
print(public)
print(private)

('xwfBg1VdrBNICQgtQ07r',)
('gxm2IMaoAVDs43auXgAv0Cuq6YPaIw',)

In [3]:
public  = mk.EDF_X()['Client'],# EDFX public key
private = mk.EDF_X()['Client_Secret'], # EDFX private key.
# testing Endpoint class instantiation 
endpoints = EDFXEndpoints(public,private)
print(endpoints)

<EDFXPrime.EDFXEndpoints object at 0x000002BC7834C970>

## Test Headers

In [4]:
# this works. feel free to test.
endpoints.EDFXHeaders(process_id='processIdTest')['ModelInputsUploadProcess']['headers']

2023-09-14 10:28:44,996 [INFO] Security token has been generated.
2023-09-14 10:28:44,996 [INFO] Security token has been generated.
2023-09-14 10:28:44,996 [INFO] Security token has been generated.
2023-09-14 10:28:44,996 [INFO] Security token has been generated.

{'x-amz-tagging': 'edfx_process_id=processIdTest', 'content-type': 'text/csv'}

# Search Endpoints

Within this package, just as the guide describes you feed the params. 
you have to at least provide a query. Example with all params, 

payload = {
    "query": "Apple Inc",
    "limit": 20,
    "offset": 0
}

### I PLACE DOCSTRING ON ALL MY METHODS SO CHECK THEM SO YOU KNOW THE PARAMS

In [4]:

#check2
response = endpoints.EDFXEntitySearchEndpoint("AAPL")
df = endpoints.EDFXSearchParse(response)
df

2023-09-22 14:25:49,554 [INFO] Security token has been generated.
2023-09-22 14:25:49,554 [INFO] Security token has been generated.
2023-09-22 14:25:49,554 [INFO] Security token has been generated.
2023-09-22 14:25:49,554 [INFO] Security token has been generated.

,entityId,internationalName,countryName,entityType,primaryIndustryNACE,primaryIndustryNAICS,contactCity,entitySize,latestPdModel,isin,...,entityIdentifierCortera,entityIdentifierEuropeanVatNumber,entityIdentifierSirenNumber,entityIdentifierTaxNumber,entityIdentifierVatNumber,entityIdentifierSiretNumber,entityIdentifierMadeUniqueId,entityIdentifierNip,entityIdentifierRegonNumber,entityIdentifierAcn
0,US942404110,"APPLE, INC.",United States of America,Corporate,2630,334220,Cupertino,4 - Very Large,lna31,US0378331005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CALEI2287956,Apple (AAPL) Yield Shares,Canada,Mutual and pension fund/Nominee/Trust/Trustee,,,Toronto,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USLEI2193308,Direxion Daily AAPL Bull 1.5X Shares,United States of America,Mutual and pension fund/Nominee/Trust/Trustee,,,Wilmington,1 - Small,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USLEI2147862,GraniteShares 1.75x Long AAPL Daily ETF,United States of America,Mutual and pension fund/Nominee/Trust/Trustee,,,Wilmington,1 - Small,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US133469770L,Aapliance Care,United States of America,Corporate,,,Vista,1 - Small,,NaN,...,133469770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,USLEI2193126,Direxion Daily AAPL Bear 1X Shares,United States of America,Mutual and pension fund/Nominee/Trust/Trustee,,,Wilmington,1 - Small,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,USLEI2239545,YieldMax AAPL Option Income Strategy ETF,United States of America,Mutual and pension fund/Nominee/Trust/Trustee,,,Wilmington,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,FR834680399,Aapl,France,Corporate,68.20,531190,Issy Les Moulineaux,1 - Small,ben10,NaN,...,NaN,FR80 834680399,834680399,834680399,FR80 834680399,834680399-00013,NaN,NaN,NaN,NaN
8,US375810203L,Aapl LLC,United States of America,Corporate,,,Wheeling,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,INA002415745,Aapl Dukan,India,Corporate,87.90,623990,Sangli,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,US368689301L,Aapl INC,United States of America,Corporate,,,Wilmington,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,US369922082L,"Aapl International, LLC",United States of America,Corporate,,,Lewes,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,US112181067GN,Aapl International LLC,United States of America,Corporate,82.99,561499,Chevy Chase,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,US112181067GN,NaN,NaN,NaN
13,US266512271L,"Aapl 75987, LLC",United States of America,Corporate,52.22,488390,Lakeway,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PL242869992,Andrzej Luszczak Aapl,Poland,Corporate,33.14,811412,Katowice,1 - Small,ben10,NaN,...,NaN,PL9541233418,NaN,9541233418,NaN,NaN,NaN,9541233418,242869992,NaN
15,AU620693816-B0005,Aapl Pty Ltd,Australia,Corporate,,,Notting Hill,1 - Small,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,US318351866L,Aapl Logistics LLC,United States of America,Corporate,49.39,485999,Doral,1 - Small,ben10,NaN,...,NaN,NaN,NaN,81-1388575,NaN,NaN,NaN,NaN,NaN,NaN
17,AU620693816,Aapl Pty Ltd,Australia,Corporate,,,Burwood East,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,620 693 816
18,INA001812396,Aapl Consulting Engineers,India,Corporate,71.11,541310,Ernakulam,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,US362179391L,"Aapl Management, LLC",United States of America,Corporate,,,Glendale,1 - Small,ben10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Batch Endpoints

In [26]:
##DOLLARDAY2023!
 # print(dir(endpoints))
query = [{ "entityIdentifierPartitaIva": 1959680388 }, { "entityIdentifierCodiceFiscale": 860340157 }, { "lei": "549300CRVT18MXX0AG93" }, { "cusip": 594918 }, { "isin": "US3453708600" }, { "entityInternationalName": "FORD MOTOR CO." }, { "pid": "34537A" }]
print("Query Object Example:")
print(query)
print("\n")
print("BATCHOUTPUT Below ")
# Send the query style object to batch call for your scripts
batch = endpoints.EDFXBatchEntitySearch(query)
print(batch)
df = endpoints.EDFXBatchParse(batch)
df

Query Object Example:
[{'entityIdentifierPartitaIva': 1959680388}, {'entityIdentifierCodiceFiscale': 860340157}, {'lei': '549300CRVT18MXX0AG93'}, {'cusip': 594918}, {'isin': 'US3453708600'}, {'entityInternationalName': 'FORD MOTOR CO.'}, {'pid': '34537A'}]


BATCHOUTPUT Below
{'entities': [{'entityId': 'US911144442', 'pid': '594918', 'identifierOrbis': '000507951', 'identifierBvd': 'US911144442', 'primaryIndustryNACE': '5829', 'primaryIndustryNAICS': '513210', 'primaryIndustryNDY': 'N12', 'primaryIndustrySIC': '7372', 'primaryIndustryNDYDescription': 'COMPUTER SOFTWARE', 'type': 'Corporate', 'entityType': 'Corporate', 'internationalName': 'MICROSOFT CORP.', 'contactAddressLine': '', 'contactCountryCode': 'USA', 'contactPostalCode': '98052-6399', 'contactStateProvince': 'WA', 'contactCity': 'Redmond', 'countryName': 'United States of America', 'entityInternationalName': 'MICROSOFT CORP.', 'entityContactAddressLine': '', 'entityContactCountryCode': 'USA', 'entityContactPostalCode': '98052-6399', 'entityContactStateProvince': 'WA', 'entityContactCity': 'Redmond', 'entityCountryName': 'United States of America', 'entityOverviewDesc': 'Microsoft Corp. engages in the development and support of software, services, devices, and solutions. It operates through the following business segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing. The Productivity and Business Processes segment consists of Office Commercial (Office 365 subscriptions, the Office 365 portion of Microsoft 365 Commercial subscriptions, and Office licensed on-premises), Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, Office Consumer, including Microsoft 365 Consumer subscriptions, Office licensed on-premises, and other Office services, LinkedIn, including Talent Solutions, Marketing Solutions, Premium Subscriptions, Sales Solutions, and Learning Solutions, Dynamics business solutions, including Dynamics 365, comprising a set of intelligent, cloud-based applications across ERP, CRM, Customer Insights, Power Apps, and Power Automate, and on-premises ERP and CRM applications. The Intelligent Cloud segment consists of Server products and cloud services, including Azure and other cloud services, SQL Server, Windows Server, Visual Studio, System Center, and related Client Access Licenses (CALs), and Nuance and GitHub, Enterprise Services, including Enterprise Support Services, Microsoft Consulting Services, and Nuance professional services. The More Personal Computing segment consists of Windows, including Windows OEM licensing and other non-volume licensing of the Windows operating system, Windows Commercial, comprising volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings, patent licensing, and Windows Internet of Things, Devices, including Surface and PC accessories, Gaming, including Xbox hardware and Xbox content and services, comprising digital transactions, Xbox Game Pass and other subscriptions, video games, third-party video game royalties, cloud services, and advertising, Search and news advertising. The company was founded by Paul Gardner Allen and William Henry Gates, III in 1975 and is headquartered in Redmond, WA.', 'entityStatus': '', 'size': '4 - Very Large', 'entitySize': '4 - Very Large', 'ticker': 'MSFT', 'peerGroupId1': 'a9c9eef1-8986-429c-9d09-16c36735ee13', 'peerGroupId2': '1d1e0ba1-6051-413c-8950-23772603a85a', 'peerGroupId3': '74b3629f-eb9b-486b-89e2-2154bd8bb781', 'peerGroupId4': '53aa387b-8970-4b2e-a27c-d9ce85fd8f94', 'peerGroupId5': '2e4e6d8e-8306-4da2-8206-827fd5270277', 'globalParentIdentifier': 'US911144442', 'globalParentName': 'MICROSOFT CORP.', 'domesticParentName': 'MICROSOFT CORP.', 'domesticParentIdentifier': 'US911144442', 'headquartersIdentifier': '', 'headquartersName': '', 'replacementIdentifier': '', 'latestPdModel': 'lna31', 'rank': '', 'nationalId': [{'idName': 'lei', 'idValue': 'INR2EJN1ERAN0W5ZP974'}, {'idName': 'sedol', 'idValue': '2588173'}, {'idName': 'isin', 'idValue': 'US5949181045'}, {'idName': 'entityIdentifierEin', 'idValue': '91-1144442'}, {'idName': 'ticker', 'idValue': 'MSFT'}, {'idName': 'cusip', 'idValue': '594918'}, {'idName': 'entityIdentifierTaxNumber', 'idValue': '91-1144442'}, {'idName': 'entityIdentifierRssdId', 'idValue': '1650121'}, {'idName': 'entityIdentifierCik', 'idValue': '0000789019'}, {'idName': 'figi', 'idValue': 'EQ0010174300001000'}], 'hasFinancials': 'Has Full Financials', 'isPublic': True, 'isCustom': False, 'timestamp': 0, 'updated': 0, 'tenantId': '', 'entityidentifierbvd': '', 'customEntityIdentifier': None}, {'entityId': 'US380549190', 'pid': '34537A', 'identifierOrbis': '058618674', 'identifierBvd': 'US380549190', 'primaryIndustryNACE': '2920', 'primaryIndustryNAICS': '336110', 'primaryIndustryNDY': 'N05', 'primaryIndustrySIC': '3711', 'primaryIndustryNDYDescription': 'AUTOMOTIVE', 'type': 'Corporate', 'entityType': 'Corporate', 'internationalName': 'FORD MOTOR CO.', 'contactAddressLine': '', 'contactCountryCode': 'USA', 'contactPostalCode': '48126-2798', 'contactStateProvince': 'MI', 'contactCity': 'Dearborn', 'countryName': 'United States of America', 'entityInternationalName': 'FORD MOTOR CO.', 'entityContactAddressLine': '', 'entityContactCountryCode': 'USA', 'entityContactPostalCode': '48126-2798', 'entityContactStateProvince': 'MI', 'entityContactCity': 'Dearborn', 'entityCountryName': 'United States of America', 'entityOverviewDesc': 'Ford Motor Co. engages in the manufacture, distribution, and sale of automobiles. It operates through the following segments: Ford Blue, Ford Model E, and Ford Pro, Ford Next, and Ford Credit. The Ford Blue, Ford Model E, and Ford Pro segment includes the sale of Ford and Lincoln vehicles, service parts, and accessories, together with the associated costs to develop, manufacture, distribute, and service the vehicles, parts, and accessories. The Ford Next segment focuses on development costs for autonomous vehicles and related businesses, equity ownership in Argo AI, and other mobility businesses and investments. The Ford Credit segment is involved in the credit business on a consolidated basis, which is primarily vehicle-related financing and leasing activities. The company was founded by Henry Ford on June 16, 1903 and is headquartered in Dearborn, MI.', 'entityStatus': '', 'size': '4 - Very Large', 'entitySize': '4 - Very Large', 'ticker': 'F', 'peerGroupId1': '63cfb403-1028-434a-b3fa-916dc8f1f3ab', 'peerGroupId2': '6da27aa9-afd3-485a-816a-ec4d4e6c694c', 'peerGroupId3': '8841a223-ba3c-4f90-b4c1-e43006fc648f', 'peerGroupId4': 'b32be259-45fb-4ea7-a8a6-8878fb9dd0d2', 'peerGroupId5': '3e3c078e-d8dc-4d3e-859a-d84592800d11', 'globalParentIdentifier': 'US380549190', 'globalParentName': 'FORD MOTOR CO.', 'domesticParentName': 'FORD MOTOR CO.', 'domesticParentIdentifier': 'US380549190', 'headquartersIdentifier': '', 'headquartersName': '', 'replacementIdentifier': '', 'latestPdModel': 'lna31', 'rank': '', 'nationalId': [{'idName': 'entityIdentifierCik', 'idValue': '0000037996'}, {'idName': 'entityIdentifierEin', 'idValue': '38-0549190'}, {'idName': 'cusip', 'idValue': '345370'}, {'idName': 'ticker', 'idValue': 'F'}, {'idName': 'sedol', 'idValue': '2615468'}, {'idName': 'figi', 'idValue': 'EQ0010060200001000'}, {'idName': 'lei', 'idValue': '20S05OYHG0MQM4VUIC57'}, {'idName': 'entityIdentifierTaxNumber', 'idValue': '38-0549190'}, {'idName': 'isin', 'idValue': 'US3453708600'}], 'hasFinancials': 'Has Full Financials', 'isPublic': True, 'isCustom': False, 'timestamp': 0, 'updated': 0, 'tenantId': '', 'entityidentifierbvd': '', 'customEntityIdentifier': None}], 'total': 2, 'relation': 'eq'}

,entityId,pid,identifierOrbis,identifierBvd,primaryIndustryNACE,primaryIndustryNAICS,primaryIndustryNDY,primaryIndustrySIC,primaryIndustryNDYDescription,type,...,nationalId_lei,nationalId_sedol,nationalId_isin,nationalId_entityIdentifierEin,nationalId_ticker,nationalId_cusip,nationalId_entityIdentifierTaxNumber,nationalId_entityIdentifierRssdId,nationalId_entityIdentifierCik,nationalId_figi
0,US911144442,594918,000507951,US911144442,5829,513210,N12,7372,COMPUTER SOFTWARE,Corporate,...,INR2EJN1ERAN0W5ZP974,2588173,US5949181045,91-1144442,MSFT,594918,91-1144442,1650121,0000789019,EQ0010174300001000
1,US380549190,34537A,058618674,US380549190,2920,336110,N05,3711,AUTOMOTIVE,Corporate,...,20S05OYHG0MQM4VUIC57,2615468,US3453708600,38-0549190,F,345370,38-0549190,NaN,0000037996,EQ0010060200001000

In [8]:
# Static batch to .csv->Works on  local machine
csv = endpoints.EDFXBatchParse(batch, "Csv")

Data Saved to batchoutput.csv

In [12]:
# StaticBatch to .excel -> works on local machine
excel = endpoints.EDFXBatchParse(batch, 'excel')

Data saved to batchoutput.xlsx

# Client Financial Template xlsx to csv:
- Bryan make this in October

# PD Endpoints:  
- 1 entity with no history
- 1 entity with timeseries interval
- multiple entities all with current term structure
- multiple entities all with time series intervals
- Parsing via static methods

In [ ]:
# works
pd_single_check = endpoints.EDFXPD_Endpoint([{ "entityId": "AT9110116332" }], endDate='2023-05-19', historyFrequency="monthly")
pd_single_check

In [5]:
#Works
pd_singlehistory = endpoints.EDFXPD_Endpoint([{ "entityId": "AT9110116332" }], startDate = "2022-01-01", endDate = "2023-05-19")
single_pdParsehistory = endpoints.EDFXPDParse(pd_singlehistory,TimeSeries=True)
single_pdParsehistory.head()

,entityId,asOfDate,pd,impliedRating,legalForm,legalStatus,legalStatusDate,confidence,confidenceDescription,forward_forward1y,...,history_impliedRating_impliedRating1y,history_impliedRating_impliedRating2y,history_impliedRating_impliedRating3y,history_impliedRating_impliedRating4y,history_impliedRating_impliedRating5y,history_impliedRating_impliedRating6y,history_impliedRating_impliedRating7y,history_impliedRating_impliedRating8y,history_impliedRating_impliedRating9y,history_impliedRating_impliedRating10y
0,AT9110116332,2023-05-01,0.002234,Baa1,LimitedLiabilityCompany,,None,PF-X-R-FLAG_S,"Private firm, RiskCalc model with full financi...",0.002234,...,Baa1,A3,A3,A3,A3,A3,Baa1,Baa1,Baa1,Baa2
1,AT9110116332,2023-05-01,0.002234,Baa1,LimitedLiabilityCompany,,None,PF-X-R-FLAG_S,"Private firm, RiskCalc model with full financi...",0.002234,...,A3,A3,A3,A3,A3,A3,Baa1,Baa1,Baa1,Baa2
2,AT9110116332,2023-05-01,0.002234,Baa1,LimitedLiabilityCompany,,None,PF-X-R-FLAG_S,"Private firm, RiskCalc model with full financi...",0.002234,...,Baa1,A3,A3,A3,A3,A3,Baa1,Baa1,Baa1,Baa2
3,AT9110116332,2023-05-01,0.002234,Baa1,LimitedLiabilityCompany,,None,PF-X-R-FLAG_S,"Private firm, RiskCalc model with full financi...",0.002234,...,Baa1,Baa1,A3,A3,A3,Baa1,Baa1,Baa1,Baa1,Baa2
4,AT9110116332,2023-05-01,0.002234,Baa1,LimitedLiabilityCompany,,None,PF-X-R-FLAG_S,"Private firm, RiskCalc model with full financi...",0.002234,...,Baa1,Baa1,A3,A3,A3,Baa1,Baa1,Baa1,Baa1,Baa2

In [6]:
# Multiple PDs: Works
MultiplePDCheck = endpoints.EDFXPD_Endpoint( [{ "entityId": "DELEI421244" }, { "entityId": "US800890963" }, { "entityId": "FR813755949" }],startDate='2022-01-01', endDate='2023-05-19', historyFrequency="monthly")
# Parse: I need to Add the Time Series COmponent
widedf=endpoints.EDFXPDParse(MultiplePDCheck,FormatType='wide', TimeSeries=True)
widedf.head()

,entityId,asOfDate,pd,impliedRating,legalForm,legalStatus,legalStatusDate,confidence,confidenceDescription,forward_forward1y,...,history_15_confidenceDescription,history_16_modelId,history_16_asOfDate,history_16_pd,history_16_impliedRating,history_16_legalForm,history_16_legalStatus,history_16_legalStatusDate,history_16_confidence,history_16_confidenceDescription
0,FR813755949,2023-05-01,0.011675,Ba2,Government,Active,NaN,PN-X-X-FLAG_S,Private firm benchmark model with no financial...,0.011675,...,Private firm benchmark model with no financial...,hmark,2023-05-01,0.011675,Ba2,Government,Active,NaN,PN-X-X-FLAG_S,Private firm benchmark model with no financial...
1,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Private firm benchmark model with no financial...,hmark,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...
2,US800890963,2023-04-30,0.034359,B1,NaN,NaN,NaN,P-G-R,"Public firm, CreditEdge model. Based on recent...",0.033807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# this is traditional EDF-X output
longdf = endpoints.EDFXPDParse(MultiplePDCheck,FormatType='long', TimeSeries=True)
longdf.head()

,entityId,asOfDate,pd,impliedRating,legalForm,legalStatus,legalStatusDate,confidence,confidenceDescription,forward_forward1y,...,history_impliedRating_impliedRating1y,history_impliedRating_impliedRating2y,history_impliedRating_impliedRating3y,history_impliedRating_impliedRating4y,history_impliedRating_impliedRating5y,history_impliedRating_impliedRating6y,history_impliedRating_impliedRating7y,history_impliedRating_impliedRating8y,history_impliedRating_impliedRating9y,history_impliedRating_impliedRating10y
0,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Ba1,Ba1,Ba1,Ba1,Ba1,Ba2,Ba2,Ba3,Ba3,Ba3
1,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Ba1,Ba1,Ba1,Ba1,Ba1,Ba2,Ba2,Ba3,Ba3,Ba3
2,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Ba1,Ba1,Ba1,Ba1,Ba1,Ba2,Ba2,Ba3,Ba3,Ba3
3,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Ba1,Ba1,Ba1,Ba1,Ba1,Ba2,Ba2,Ba3,Ba3,Ba3
4,DELEI421244,2023-05-01,0.010603,Ba1,Government,Active,NaN,PN-X-X-FLAG_T,Private firm benchmark model with no financial...,0.010603,...,Ba1,Ba1,Ba1,Ba1,Ba1,Ba2,Ba2,Ba3,Ba3,Ba3

In [ ]:
#Multiple PDs TimeSeries: Works
MultiplePDTimeSeriesCheck = endpoints.EDFXPD_Endpoint( [{ "entityId": "DELEI421244" }, { "entityId": "US800890963" }, { "entityId": "FR813755949" }], startDate = '2022-01-01',endDate='2023-05-19', historyFrequency="monthly")
MultiplePDTimeSeriesCheck 
#Georgie put Times Series PARSE HERE

In [ ]:
#To CSV doesn't need to be case sensative, long version to .csv
endpoints.EDFXPDParse(MultiplePDCheck,FormatType='long',output_format='Csv')
# to Excel. wide version, .xlsx vile. 
endpoints.EDFXPDParse(MultiplePDCheck,FormatType='wide',output_format='Excel')

# Process ID example
## CLient Provides us 100 IDS and would like to See how PD's from the id list on EDF-X API. 

- This is a quick and dirty way we can accomplish this task.

In [18]:
# Take the first 100 IDs from a .csv file a client gives us
ids = pd.read_csv('TESTBvD_ID_Bulk_Upload.csv')['Identifier*'][:100]
# these are params: Run time is awful on this. 
entities = [{"entityId": i } for i in ids]
print(entities)
try:
    pd_multiple_check = endpoints.EDFXPD_Endpoint(entities=entities, startDate = '2022-01-01',endDate='2023-05-19', historyFrequency="monthly")
    if pd_multiple_check['processId']:
        print(f"Process ID:, {pd_multiple_check['processId']}")
        processPD = endpoints.EDFXPD_History(startDate = '2022-01-01',endDate='2023-05-19', historyFrequency="monthly",processId = pd_multiple_check['processId'])
        print(processPD)
    else:
        pd_multiple_check
except Exception as e:
    print(f'An error occured: {e}.')
        
#  This output is bullshit. They can't all be/all have no data for the time series

[{'entityId': 'US323860652L'}, {'entityId': 'US160292205L'}, {'entityId': 'US123417067L'}, {'entityId': 'US174025515L'}, {'entityId': 'US245243012L'}, {'entityId': 'US250123655L'}, {'entityId': 'US150238251L'}, {'entityId': 'US123854753L'}, {'entityId': 'US149111951L'}, {'entityId': 'US131874864L'}, {'entityId': 'US240402245L'}, {'entityId': 'US296645003L'}, {'entityId': 'US149207136L'}, {'entityId': 'US292929686L'}, {'entityId': 'US127922266L'}, {'entityId': 'US127420802L'}, {'entityId': 'US134001297L'}, {'entityId': 'US132101398L'}, {'entityId': 'US349185794L'}, {'entityId': 'US132912437L'}, {'entityId': 'US187108254L'}, {'entityId': 'US295894427L'}, {'entityId': 'US295708856L'}, {'entityId': 'US295708856L'}, {'entityId': 'US276599246L'}, {'entityId': 'US241497443L'}, {'entityId': 'US317725418L'}, {'entityId': 'US248669717L'}, {'entityId': 'US305054801L'}, {'entityId': 'US320056778L'}, {'entityId': 'US620516475'}, {'entityId': 'US168302388L'}, {'entityId': 'US290586179L'}, {'entityId': 'US128433974L'}, {'entityId': 'US165114066L'}, {'entityId': 'US860419443'}, {'entityId': 'US303406514L'}, {'entityId': 'US203195377'}, {'entityId': 'US229443509L'}, {'entityId': 'US149203124L'}, {'entityId': 'US731371046'}, {'entityId': 'US298478474L'}, {'entityId': 'US353578319L'}, {'entityId': 'US160881279L'}, {'entityId': 'US130407758L'}, {'entityId': 'US281154515L'}, {'entityId': 'US303255965L'}, {'entityId': 'US132097597L'}, {'entityId': 'US305289449L'}, {'entityId': 'US133958143L'}, {'entityId': 'US*956128886'}, {'entityId': 'US292929686L'}, {'entityId': 'US292929686L'}, {'entityId': 'US258114980L'}, {'entityId': 'US236793965L'}, {'entityId': 'US353868665L'}, {'entityId': 'US127217228L'}, {'entityId': 'US130852772L'}, {'entityId': 'US042723701'}, {'entityId': 'US731371046'}, {'entityId': 'US120030488L'}, {'entityId': 'US256726814L'}, {'entityId': 'US127691052L'}, {'entityId': 'US304447139L'}, {'entityId': 'US132417855L'}, {'entityId': 'US125665023L'}, {'entityId': 'US231087389L'}, {'entityId': 'US331322033L'}, {'entityId': 'US276184001L'}, {'entityId': 'US292707566L'}, {'entityId': 'US263011769L'}, {'entityId': 'US125818286L'}, {'entityId': 'US127450608L'}, {'entityId': 'US277422008L'}, {'entityId': 'US352244297L'}, {'entityId': 'US126428172L'}, {'entityId': 'US296991302L'}, {'entityId': 'US161337126L'}, {'entityId': 'US120262238L'}, {'entityId': 'US354202433L'}, {'entityId': 'US128084908L'}, {'entityId': 'US232056557L'}, {'entityId': 'US145441072L'}, {'entityId': 'US258364691L'}, {'entityId': 'US348732422L'}, {'entityId': 'US114501133GN'}, {'entityId': 'US329171489L'}, {'entityId': 'US161542712'}, {'entityId': 'US166166097L'}, {'entityId': 'US294713162L'}, {'entityId': 'US293955011L'}, {'entityId': 'US128440384L'}, {'entityId': 'US125648064L'}, {'entityId': 'US164235033L'}, {'entityId': 'US275500499L'}, {'entityId': 'US324242168L'}, {'entityId': 'US316320377L'}, {'entityId': 'US280696730L'}, {'entityId': 'US129275666L'}, {'entityId': 'US127691052L'}]
Process ID:, e37c4862-5316-11ee-9426-62929ad7e856
{'entities': [{'entityId': 'e37c4862-5316-11ee-9426-62929ad7e856', 'message': 'No data found in the given date range'}]}

# Financial Template Download + Parse
endpoint

In [5]:
universal = endpoints.EDFXTemplateDownload(financialtemplate = 'Universal',output_format='Csv')

Data Saved to SearchOutput.csv

# Test Upload

## ModelInputs

In [6]:
# Create model inputs process
model_inputs_response = endpoints.EDFXModelInputs(uploadFilename='BryansCustomTarget', localFilename='BryansCustomTarget.csv')
model_inputs_response

200

{'processId': 'b675bf9a-5c6d-42bf-ae94-747b47167e51',
 'uploadLink': 'https://uswe2-edfx-clientfinancials-shared-101.s3.amazonaws.com/prd/input/validate/test_006?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA4VIHTIBMKP5A2UF4%2F20230814%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230814T224818Z&X-Amz-Expires=300&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-tagging&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEH8aCXVzLXdlc3QtMiJHMEUCIQDpVtFU5H7EK%2F3XMsLL4q%2FnHsGR6fN8hcZ3hpftgIlTVwIgF10drxh1q9a11UpypO0cTJvfYncC2VnI%2BLThMv581KMqlQMIOBACGgw4NzAyODM2OTAwNzIiDNof7XxZCSJ04R7D3yryAukGvEU8kKeNLSVwPjGgI1nV%2F4wdddaP6wEf%2FQ%2BSPsw1exECO%2B8Eg317mm3HtgLyzB3rps7uZjqQeG1oFwZPu0fZtNUjyKjEk9uYLAIc0BIEz8Umn82%2B7y1TfewU4e1I618nr2m8ReQd7tbufOB%2F5dghRIE9I2PYL0yJbxICMT1g8yoWCW0lgAtlsiH6bjZt8cAPRYDEylLoZWvnH0fxpGM7yKHY3GLk%2BYEbliro%2BOIn0mjq7zOUMl4f8e4g4CJF%2Bu5d6FrShTxhdUeAppbUUsvyZgGdYLO8rHFsnakL3x4gkqeQ9swYkXYjIWp4t0ahFNoDfXSKahn9o1r1oeh1%2FsokLbLRqt9xRgWOtBIWBcCmeOcMBkzbQfR4MKSrKqz6ZQlo4mJJmRikbpXRLjViXyc47xydnkugVdY17hK2zxn9j%2FgfW5Z9q%2FHYYsnHsTqFuJFKuwsJVRAOzaWfL9sh2Psl5JAxkM9pl4iBX3pp%2F4Xf4iUwytjqpgY6nQFDk40GrLWiv5eX4gyFQ7g5jfROomIZJ8fKdY61XtjfOE5adZgAFx3LhZSaJKbJMAnM5ryM4sPcFzeQGO54rd5cB%2FZRcfC9GLQEfm3e2oQO8cALJIlqsClmBFXjooe%2BCanRgvU1Q%2F4gL9zn0hE%2FXoBxt%2BnKwh0TwsZaae4%2Ba2wqLntkf13jKPFu4ngl%2BfT0AMP6%2F5ps3pDaaG%2FS54M9&X-Amz-Signature=2042c8d380b47de40403ae1033f47def55da5c5b59f2d38151b6f8a3d13756b6'}

## Upload File
## Check Server
- This takes too long and errors out so the file i'm using is too large.

In [11]:
MAX_RETRIES = 30  # or however many retries you think is appropriate

# If a model input process was created we will start checking the process status every 20 seconds until it completes
if model_inputs_response:
    retries = 0
    while retries < MAX_RETRIES:
        model_inputs_process_status = endpoints.EDFXModelInputsGetStatus(processID=model_inputs_response['processId'])
        if model_inputs_process_status is None:
            print('No process status returned.')
            break
        if model_inputs_process_status['status'] == 'Processing':
            print('Model is still processing, retrying in 1 minute')
            time.sleep(60)  # wait 60 seconds and try again
            retries += 1
        else:
            # This seems to be erroring out/not receiving the file. 
            print('Model processing finished, getting files')
            files = endpoints.EDFXModelInputsGetFiles(processID=model_inputs_response['processId'])
            print(files.text)
            break
    else:
        print(f"Max retries ({MAX_RETRIES}) reached. Exiting loop.")
else:
    print('No model input response')

Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Model is still processing, retrying in 1 minute
Max retries (30) reached. Exiting loop.

# Using a process id we already created to test without having to wait

In [8]:
process_id = 'b675bf9a-5c6d-42bf-ae94-747b47167e51'
status = endpoints.EDFXModelInputsGetStatus(processID=process_id)
print(f'Status: {status}')
# If the process status is not "Processing" try to download the file.
# NOTE: We assume the downloaded file format is CSV, this may not be true
if status and status['status'] != 'Processing':
    print('Model processing finished, getting files')
    files = endpoints.EDFXModelInputsGetFiles(processID=process_id)
    print(files)
    with open(f'{process_id}.csv', 'w') as f:
        f.write(files)
else:
    print('Try again later')

Status: {'status': 'Processing'}
Try again later

# Test Multiple PDs

# Retrieving LImits for Trade Credit

In [6]:

# test1 = endpoints.EDFXRetrievinglimtsfortradecredit([{ "entityId": "AT9110116332" }])
# test1
# when I include all params it works.  
trade_credit = endpoints.EDFXRetrievinglimtsfortradecredit([{ "entityId": "DELEI421244" }, { "entityId": "US800890963" }, { "entityId": "FR813755949" }], startDate='2021-01-01', endDate="2021-06-09")
trade_parse = endpoints.EDFXParseTradeCredit(trade_credit)
trade_parse

Unfortunately: FR813755949 has no credit information.
Unfortunately: DELEI421244 has no credit information.

,entityId,asOfDate,pd,balanced,aggressive,conservative,currency,unit
0,US800890963,2021-06-01,0.041134,11348809.97,17673627.57,5023992.37,USD,1
1,US800890963,2021-05-01,0.043073,10941912.39,17073089.00,4810735.77,USD,1
2,US800890963,2021-04-01,0.039239,11783526.56,18316121.02,5250932.09,USD,1
3,US800890963,2021-03-01,0.040737,11436683.37,17803430.50,5069936.24,USD,1
4,US800890963,2021-02-01,0.047307,10164754.69,15928835.46,4400673.92,USD,1
5,US800890963,2021-01-01,0.063793,8085690.15,12895637.68,3275742.62,USD,1

In [6]:
# trade_parse = endpoints.EDFXParseTradeCredit(trade_credit, output_format = 'csv')
# trade_parse = endpoints.EDFXParseTradeCredit(trade_credit, output_format = 'excel')

Unfortunately: DELEI421244 has no credit information.
Unfortunately: FR813755949 has no credit information.
Data Saved to PDs.csv
Unfortunately: DELEI421244 has no credit information.
Unfortunately: FR813755949 has no credit information.
Data saved to PDs.xlsx

# Retrieving Peer Groups

In [7]:
# Does not work,  {'message': 'Internal server error'}
# endpoints.EDFXRetrievingpeergroups_IDS(peerRegion='WESTEUR', ownershipType='LISTED')
# This worked. THis is bullshit.  they need industryCode and Industry CLassification
endpoints.EDFXRetrievingpeergroups_IDS(peerRegion='WESTEUR', ownershipType='LISTED',industryCode="N55", industryClassification='NDY')

{'results': [{'peerId': 'c45ac44c-14cc-4e07-87f7-08fefa10f788'}]}

In [8]:
# works with all variables.
json = endpoints.EDFXRetrievingpeergroups_Metrics(peerId="832ec933-28e0-47c9-85a2-a8b5c2ca02b5",metrics=["P025", "P050"], 
                                                    variables=["annualizedcumulativepd1y"],startDate="2022-11-01", endDate="2023-01-01")

# Metrics_csv = endpoints.ParsePeerGroupMetrics(json, output_format= "csv")
# Metrics_xlsx = endpoints.ParsePeerGroupMetrics(json, output_format= "excel")
Metrics = endpoints.EDFXParsePeerGroupMetrics(json)
Metrics

      P025      P050    asOfDate              variableName  unit currency
0  0.00316  0.011863  2022-11-01  annualizedcumulativepd1y  0.01     None
1  0.00297  0.014730  2022-12-01  annualizedcumulativepd1y  0.01     None
2  0.00361  0.016065  2023-01-01  annualizedcumulativepd1y  0.01     None

In [9]:
json = endpoints.EDFXRetrievingpeergroups_Percentile("832ec933-28e0-47c9-85a2-a8b5c2ca02b5",["annualizedcumulativepd1y"],[.025] )
percentile_parse = endpoints.EDFXParsePeerGroupPercentile(json)
percentile_parse

               variableName percentile
0  annualizedcumulativepd1y       P065

In [11]:
json = endpoints.EDFXRetrievingpeergroups_Metadata("6cef0ad5-5f1b-40bc-85a9-0a071143fd3b")

,peerId,peerName,count,country,region,industryCode,ownershipType
0,6cef0ad5-5f1b-40bc-85a9-0a071143fd3b,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,73554,GBR,None,N09,UNLISTED

In [18]:
json = endpoints.EDFXRetrievingpeergroups_Recommended(industryClassification='NDY', industryCode="N17",ownershipType="UNLISTED", country="USA")
df

  peerId_name                          peerId_value
0      peerId  e618741f-c297-43f2-8a86-916920ce21c1
1     peerId2  58e79456-390a-482f-bd8a-a7fe515cf9c8
2     peerId3  7bf6fd00-66f6-4643-b02c-08b04d52a256
3     peerId4  302a04c3-3223-4f65-b93d-fe4da81ca00a
4     peerId5  f472b9f5-94e1-485a-8dd0-4405d10dff36

# Retrieving Risk Category

In [5]:
# Get the risk category for specific entity or list of entities
risk_categories = endpoints.EDFXRetrievingRiskCategory(entities=[{"entityId":"US911144442"}])
print(risk_categories)

# Parse the retrieved risk category into Pandas Dataframe
parsed_risk_categories = endpoints.EDFXRiskCategoryParse(risk_categories)
print(parsed_risk_categories)

2023-09-07 13:12:36,007 [INFO] Security token has been generated.
2023-09-07 13:12:36,007 [INFO] Security token has been generated.
2023-09-07 13:12:36,007 [INFO] Security token has been generated.
2023-09-07 13:12:36,007 [INFO] Security token has been generated.

[{'entityId': 'US911144442', 'peerId': 'a9c9eef1-8986-429c-9d09-16c36735ee13', 'asOfDate': '2023-09-01', 'prevAsOfDate': '2022-09-01', 'irChange': 0, 'trigger': 0.05362249881692241, 'pd': 0.000221, 'riskCategory': 'Low', 'distanceToTrigger': -5.491561311516115}]
      entityId                                peerId    asOfDate prevAsOfDate  \
0  US911144442  a9c9eef1-8986-429c-9d09-16c36735ee13  2023-09-01   2022-09-01

   irChange   trigger        pd riskCategory  distanceToTrigger
0         0  0.053622  0.000221          Low          -5.491561